# This is a basic workflow to help you get started with Actions

# Controls when the workflow will run
on:
  schedule:
    # * 00：00 UTC+8 everyday
    - cron:  '0 16 * * *'
permissions:
  contents: write
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "get"
  get:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Runs a single command using the runners shell
      - name: Run a python script
        run: python3 GetCiteNum.py

      - name: Commit changes
        run: |
          git config --global user.name 'CiteNumBot'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Update number of references"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}